"""change code from integer value to string value

Revision ID: 0daf27ffb7c3
Revises: 3728b5162d48
Create Date: 2025-09-04 10:04:16.766174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0daf27ffb7c3'
down_revision = '3728b5162d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('constituencies', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('counties', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('counties', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('constituencies', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
