"""make party id in Terms nullable

Revision ID: 8655a1bfbc30
Revises: 0daf27ffb7c3
Create Date: 2025-09-07 01:09:12.128536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8655a1bfbc30'
down_revision = '0daf27ffb7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.alter_column('party_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.alter_column('party_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
