"""update table args for position

Revision ID: b744aa13027f
Revises: 8655a1bfbc30
Create Date: 2025-09-07 07:39:29.407762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b744aa13027f'
down_revision = '8655a1bfbc30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_positions_level_valid", "positions", type_="check")
    op.create_check_constraint(
        "ck_positions_level_valid",
        "positions",
        "level IN ('national','county','constituency','ward')"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_positions_level_valid", "positions", type_="check")
    op.create_check_constraint(
        "ck_positions_level_valid",
        "positions",
        "level IN ('national','county','ward')"
    )
    # ### end Alembic commands ###
