"""Initial migration

Revision ID: cd48837e15d4
Revises: 
Create Date: 2025-08-31 22:51:45.746383

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'cd48837e15d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('population_density', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('counties', schema=None) as batch_op:
        batch_op.create_index('idx_counties_geom', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
        batch_op.create_index('ix_counties_name', [sa.literal_column('lower(name)')], unique=False)

    op.create_table('officials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("gender IN ('male','female','other')", name='ck_officials_gender_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('officials', schema=None) as batch_op:
        batch_op.create_index('ix_officials_name', [sa.literal_column('lower(name)')], unique=False)

    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('colors', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.create_index('ix_parties_name', [sa.literal_column('lower(name)')], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("level IN ('national','county','ward')", name='ck_positions_level_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('ix_positions_name', [sa.literal_column('lower(name)')], unique=False)

    op.create_table('constituencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('population_density', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name', 'county_id', name='uq_constituencies_name_per_county')
    )
    with op.batch_alter_table('constituencies', schema=None) as batch_op:
        batch_op.create_index('idx_constituencies_geom', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
        batch_op.create_index('ix_constituencies_name', [sa.literal_column('lower(name)')], unique=False)

    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('constituency_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name', 'constituency_id', name='uq_wards_name_per_constituency')
    )
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.create_index('idx_wards_geom', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
        batch_op.create_index('ix_wards_name', [sa.literal_column('lower(name)')], unique=False)

    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('constituency_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('nomination_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_year IS NULL OR end_year >= start_year', name='ck_terms_end_year_after_start'),
    sa.CheckConstraint('start_year > 1900', name='ck_terms_start_year_valid'),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['official_id'], ['officials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.create_index('ix_terms_official', ['official_id'], unique=False)
        batch_op.create_index('ix_terms_years', ['start_year', 'end_year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_index('ix_terms_years')
        batch_op.drop_index('ix_terms_official')

    op.drop_table('terms')
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.drop_index('ix_wards_name')
        batch_op.drop_index('idx_wards_geom', postgresql_using='gist')

    op.drop_table('wards')
    with op.batch_alter_table('constituencies', schema=None) as batch_op:
        batch_op.drop_index('ix_constituencies_name')
        batch_op.drop_index('idx_constituencies_geom', postgresql_using='gist')

    op.drop_table('constituencies')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('ix_positions_name')

    op.drop_table('positions')
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_index('ix_parties_name')

    op.drop_table('parties')
    with op.batch_alter_table('officials', schema=None) as batch_op:
        batch_op.drop_index('ix_officials_name')

    op.drop_table('officials')
    with op.batch_alter_table('counties', schema=None) as batch_op:
        batch_op.drop_index('ix_counties_name')
        batch_op.drop_index('idx_counties_geom', postgresql_using='gist')

    op.drop_table('counties')
    # ### end Alembic commands ###
