"""update unique constraints on Ward

Revision ID: e0c404832fc0
Revises: b744aa13027f
Create Date: 2025-11-12 22:55:03.856646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c404832fc0'
down_revision = 'b744aa13027f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_wards_name_per_constituency'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_wards_name_per_constituency'), ['name', 'constituency_id'])

    # ### end Alembic commands ###
